---
- name: Check if Netdata container already exists
  shell: docker ps -a --format '{{ '{{' }}.Names{{ '}}' }}' --filter "name={{ monitoring_container_name }}"
  register: netdata_exists
  changed_when: false
  failed_when: false

- name: Remove existing Netdata container if exists
  command: docker rm -f {{ monitoring_container_name }}
  when: netdata_exists.stdout != ""

- name: Ensure Netdata go.d directory exists
  file:
    path: "{{ monitoring_config_path }}/go.d"
    state: directory
    mode: '0755'

- name: Configure Netdata nvme monitoring
  template:
    src: nvme.conf.j2
    dest: "{{ monitoring_config_path }}/go.d/nvme.conf"
    mode: '0644'

- name: Start Netdata container
  command: >
    docker run -d
    --name={{ monitoring_container_name }}
    -p 0.0.0.0:{{ monitoring_port }}:19999
    -v netdata-data:/var/lib/netdata
    -v netdata-config:/etc/netdata
    --cap-add SYS_PTRACE
    --security-opt apparmor=unconfined
    --restart unless-stopped
    {{ monitoring_image }}
  when: monitoring_install | default(true)

