---
# Portainer configuration
portainer_install: true
portainer_takeover: false  # Ustaw na true aby przejąć istniejący Portainer
portainer_container_name: portainer
portainer_port: 9000
portainer_image: portainer/portainer-ce:2.39.5  # przypięte 2026-09-13
portainer_data_dir: /srv/portainer/data  # Na sda (system)
portainer_compose_dir: ~/stacks/portainer
portainer_network: portainer_network

