---
- name: restart docker
  systemd:
    name: docker
    state: restarted
  when: docker_install | default(false)

- name: restart systemd-journald
  systemd:
    name: systemd-journald
    state: restarted

- name: reload systemd
  command: systemctl daemon-reload
