---
- name: restart docker
  systemd:
    name: docker
    state: restarted
  when: docker_install | default(false)

- name: restart systemd-journald
  systemd:
    name: systemd-journald
    state: restarted

- name: reload systemd
  command: systemctl daemon-reload

- name: restart k3s
  systemd:
    name: k3s
    state: restarted
  when: k3s_restrict_api | default(false)

- name: restart native netdata
  systemd:
    name: netdata
    state: restarted
  failed_when: false
