---
# Ścieżki i ustawienia stacka Prometheus + Grafana
prom_stack_dir: "{{ ansible_env.HOME }}/stacks/observability"
prom_docker_network: observability

# Obrazy
prom_image: prom/prometheus:latest
grafana_image: grafana/grafana:latest
node_exporter_image: prom/node-exporter:latest
cadvisor_image: gcr.io/cadvisor/cadvisor:latest
blackbox_image: prom/blackbox-exporter:latest
postgres_exporter_image: prometheuscommunity/postgres-exporter:latest

# Porty publiczne
prometheus_port: 9090
grafana_port: 3000
node_exporter_port: 9103
cadvisor_port: 9102
blackbox_port: 9115

# Grafana admin (można nadpisać w secrets.yml)
grafana_admin_user: admin
grafana_admin_password: admin


