- hosts: web
  become: true
  vars_files:
    - "{{ inventory_dir }}/group_vars/secrets.yml"
  roles:
    - common
    - fail2ban
    - wifi
    - web
    - db
    - storage
    - postgres
    - postgres-test
    - qdrant
    - proxy
    - backups
    - monitoring
    - prometheus
    - portainer
    - app
